apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-temp-comp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-temp-comp
    app.kubernetes.io/part-of: my-test-temp-app
  name: test-temp-comp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: test-temp-comp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: test-temp-comp
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/my-test-temp-app/test-temp-comp@sha256:bcb6e72646b5fbd55b65459a6b03bd9ed3ec75282e71973f183f1db25cc463a9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
