apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testsample-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testsample-go
    app.kubernetes.io/part-of: my-test-temp-app
  name: testsample-go
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: testsample-go
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: testsample-go
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/my-test-temp-app/testsample-go@sha256:23fc07465d82c34edcd77a36c9d7a2c2c7c33bc20c1f9e0a9ebef21fa6406503
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
