apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: testsample-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testsample-go
    app.kubernetes.io/part-of: my-test-temp-app
  name: testsample-go
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: testsample-go
status:
  loadBalancer: {}
