apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-2gzh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-2gzh
    app.kubernetes.io/part-of: my-test-temp-app
  name: node-express-hello-2gzh
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: node-express-hello-2gzh
status:
  loadBalancer: {}
